In [1]:
import pandas as pd
print(pd.__version__)

2.3.3

In [2]:
df=pd.read_csv("mabel.txt", header = None, on_bad_lines ="skip", encoding="utf8")
df

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [3]:
df=df.drop(0)
df.columns=["Date","Chat"]
Message = df["Chat"].str.split("-",n=1,expand=True)
df["Time"]=Message[0]
Message1=Message[1].str.split(":",n=1,expand=True)
df["Name"]=Message1[0]
df["Chat"]=Message1[1]
df=df[["Date","Time","Name","Chat"]]
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

# 1. Flirt Prediction Model

#### A) Problem Statement
With the chat history, we have to identify whether the chat person flirted or not

In [ ]:
import numpy as np

In [ ]:
chat_data = df.copy()

In [ ]:
chat_data

In [ ]:
chat_data["Chat"] = chat_data["Chat"].fillna("").astype(str).str.strip()

In [ ]:
chat_data = chat_data[chat_data["Chat"] != ""].copy()

In [ ]:
chat_data = chat_data.reset_index(drop=True)

In [ ]:
chat_data["Message_ID"] = chat_data.index

In [ ]:
label_data = chat_data[["Message_ID", "Chat"]].copy()

In [ ]:
label_data["Flirt_Label"] = ""

In [ ]:
label_data.to_csv("whatsapp_messages_to_label.csv", index=False)

In [ ]:
display(label_data.head(10))

In [ ]:
print("Total messages to label:", len(label_data))
print("File created: whatsapp_messages_to_label.csv")

#### Counter Vector

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [11]:
data = pd.read_csv("whatsapp_messages_labeled.csv")
data

    Message_ID                                               Chat  Flirt_Label
0            0                     Hi this is Mabel we just spoke            0
1            1                              What’s your full name            0
2            2                                     Ramisha Rani K            0
3            3                                                 Ok            0
4            4                             ramisharanik@gmail.com            0
5            5                                     Your email Id?            0
6            6                                            Yes Mam            0
7            7     I will send 2 abstracts for u to start working            0
8            8                                           Yeah mam            0
9            9                   Give me the list that u have too            0
10          10  Send me cbe office address and phone number I ...            0
11          11    Yeah Mam within Evening I will forward you mam.            0
12          12  Tomorrow I have to visit the office.yet not I ...            0
13          13                                                 ok            0
14          14  send the details of office location once u get...            0
15          15   Sure mam. Soon I will share details with you mam            0
16          16  I have read the Abstract mam. We can do mam. N...            0
17          17  I think Vignesh has the data set will ask him ...            0
18          18                          I have sent the abstracts            0
19          19                                             Ok mam            0
20          20  I have read both the abstract mam. We can do b...            0
21          21  Yes we need to ya about amount and all other d...            0
22          22                                          Sure mam.            0
23          23                                  Shall I call mam?            1
24          24         Hi I was at church couldn’t take your call            0
25          25                                         It's k mam            0
26          26  Just to know the tomorrow plan mam.will see to...            0
27          27                    Mam can u send Vignesh number??            1
28          28           Vignesh ML Infoziant.vcf (file attached)            0
29          29                           I was in a meeting sorry            0
30          30                                    Can I cal u mam            1
31          31  Waiting for u r finalization of rates for our ...            1
32          32  If we finiliaze I can work with full involveme...            0
33          33  So what ever may be ..if you think your are co...            0
34          34                           You deleted this message            1
35          35                                     Do the needful            1
36          36  No ma please hold I am in a hot meeting with a...            0
37          37                                     Ok mam thank u            0
38          38  Ramisha we need to talk today i will call u ar...            0
39          39     Be ready to discuss about the ML titles u have            0
40          40                                           Okay mam            0
41          41                                                 ok            0
42          42                                    Mam are u free?            1
43          43   Am at church can call very late or tomorrow only            0
44          44  Kk mam. I will ask Arun brother. Small doubt ....            0
45          45                                             Hi mam            0
46          46                                   Any updates mam?            0
47          47     U might have to start on the WhatsApp analysis            0
48          48            There is one project that got committed            0
49          49                                           Kk mam👍🏻            1

In [12]:
data["Chat"] = data["Chat"].fillna("").astype(str)
data["Flirt_Label"] = pd.to_numeric(data["Flirt_Label"], errors="coerce")
data = data.dropna(subset=["Flirt_Label"])
data["Flirt_Label"] = data["Flirt_Label"].astype(int)
X = data["Chat"]
y = data["Flirt_Label"]

cv = CountVectorizer()
X_count = cv.fit_transform(X)

print("Count Vectorizer Shape:", X_count.shape)
print("Vocabulary Size:", len(cv.vocabulary_))

if y.nunique() == 2 and y.value_counts().min() >= 2:
    X_train, X_test, y_train, y_test = train_test_split(X_count, y, test_size=0.2,random_state=42, stratify=y)

    count_model = LogisticRegression(max_iter=1000)
    count_model.fit(X_train, y_train)

    y_pred = count_model.predict(X_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, zero_division=0))

    data["Count_Prediction"] = count_model.predict(X_count)
else:
    print("Classifier not trained: labels contain only one class.")
    print("Add genuine labelled examples from both classes to train.")

display(data.head())

Count Vectorizer Shape: (50, 189)
Vocabulary Size: 189
Accuracy: 0.8
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       0.00      0.00      0.00         2

    accuracy                           0.80        10
   macro avg       0.40      0.50      0.44        10
weighted avg       0.64      0.80      0.71        10

   Message_ID                            Chat  Flirt_Label  Count_Prediction
0           0  Hi this is Mabel we just spoke            0                 0
1           1           What’s your full name            0                 0
2           2                  Ramisha Rani K            0                 0
3           3                              Ok            0                 0
4           4          ramisharanik@gmail.com            0                 0

#### TF-IDF Vector

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [14]:
data = pd.read_csv("whatsapp_messages_labeled.csv")
data

    Message_ID                                               Chat  Flirt_Label
0            0                     Hi this is Mabel we just spoke            0
1            1                              What’s your full name            0
2            2                                     Ramisha Rani K            0
3            3                                                 Ok            0
4            4                             ramisharanik@gmail.com            0
5            5                                     Your email Id?            0
6            6                                            Yes Mam            0
7            7     I will send 2 abstracts for u to start working            0
8            8                                           Yeah mam            0
9            9                   Give me the list that u have too            0
10          10  Send me cbe office address and phone number I ...            0
11          11    Yeah Mam within Evening I will forward you mam.            0
12          12  Tomorrow I have to visit the office.yet not I ...            0
13          13                                                 ok            0
14          14  send the details of office location once u get...            0
15          15   Sure mam. Soon I will share details with you mam            0
16          16  I have read the Abstract mam. We can do mam. N...            0
17          17  I think Vignesh has the data set will ask him ...            0
18          18                          I have sent the abstracts            0
19          19                                             Ok mam            0
20          20  I have read both the abstract mam. We can do b...            0
21          21  Yes we need to ya about amount and all other d...            0
22          22                                          Sure mam.            0
23          23                                  Shall I call mam?            1
24          24         Hi I was at church couldn’t take your call            0
25          25                                         It's k mam            0
26          26  Just to know the tomorrow plan mam.will see to...            0
27          27                    Mam can u send Vignesh number??            1
28          28           Vignesh ML Infoziant.vcf (file attached)            0
29          29                           I was in a meeting sorry            0
30          30                                    Can I cal u mam            1
31          31  Waiting for u r finalization of rates for our ...            1
32          32  If we finiliaze I can work with full involveme...            0
33          33  So what ever may be ..if you think your are co...            0
34          34                           You deleted this message            1
35          35                                     Do the needful            1
36          36  No ma please hold I am in a hot meeting with a...            0
37          37                                     Ok mam thank u            0
38          38  Ramisha we need to talk today i will call u ar...            0
39          39     Be ready to discuss about the ML titles u have            0
40          40                                           Okay mam            0
41          41                                                 ok            0
42          42                                    Mam are u free?            1
43          43   Am at church can call very late or tomorrow only            0
44          44  Kk mam. I will ask Arun brother. Small doubt ....            0
45          45                                             Hi mam            0
46          46                                   Any updates mam?            0
47          47     U might have to start on the WhatsApp analysis            0
48          48            There is one project that got committed            0
49          49                                           Kk mam👍🏻            1

In [15]:
data["Chat"] = data["Chat"].fillna("").astype(str)
data["Flirt_Label"] = pd.to_numeric(data["Flirt_Label"], errors="coerce")
data = data.dropna(subset=["Flirt_Label"])
data["Flirt_Label"] = data["Flirt_Label"].astype(int)

X = data["Chat"]
y = data["Flirt_Label"]

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(X)

print("TF-IDF Shape:", X_tfidf.shape)
print("Vocabulary Size:", len(tfidf.vocabulary_))

if y.nunique() == 2 and y.value_counts().min() >= 2:
    X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2,random_state=42, stratify=y)

    tfidf_model = LogisticRegression(max_iter=1000)
    tfidf_model.fit(X_train, y_train)

    y_pred = tfidf_model.predict(X_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, zero_division=0))
    data["TFIDF_Prediction"] = tfidf_model.predict(X_tfidf)
else:
    print("Classifier not trained: labels contain only one class.")
    print("Add genuine labelled examples from both classes to train.")

display(data.head())

TF-IDF Shape: (50, 189)
Vocabulary Size: 189
Accuracy: 0.8
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       0.00      0.00      0.00         2

    accuracy                           0.80        10
   macro avg       0.40      0.50      0.44        10
weighted avg       0.64      0.80      0.71        10

   Message_ID                            Chat  Flirt_Label  TFIDF_Prediction
0           0  Hi this is Mabel we just spoke            0                 0
1           1           What’s your full name            0                 0
2           2                  Ramisha Rani K            0                 0
3           3                              Ok            0                 0
4           4          ramisharanik@gmail.com            0                 0

#### Hashing Vector

In [16]:
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [17]:
data = pd.read_csv("whatsapp_messages_labeled.csv")
data

    Message_ID                                               Chat  Flirt_Label
0            0                     Hi this is Mabel we just spoke            0
1            1                              What’s your full name            0
2            2                                     Ramisha Rani K            0
3            3                                                 Ok            0
4            4                             ramisharanik@gmail.com            0
5            5                                     Your email Id?            0
6            6                                            Yes Mam            0
7            7     I will send 2 abstracts for u to start working            0
8            8                                           Yeah mam            0
9            9                   Give me the list that u have too            0
10          10  Send me cbe office address and phone number I ...            0
11          11    Yeah Mam within Evening I will forward you mam.            0
12          12  Tomorrow I have to visit the office.yet not I ...            0
13          13                                                 ok            0
14          14  send the details of office location once u get...            0
15          15   Sure mam. Soon I will share details with you mam            0
16          16  I have read the Abstract mam. We can do mam. N...            0
17          17  I think Vignesh has the data set will ask him ...            0
18          18                          I have sent the abstracts            0
19          19                                             Ok mam            0
20          20  I have read both the abstract mam. We can do b...            0
21          21  Yes we need to ya about amount and all other d...            0
22          22                                          Sure mam.            0
23          23                                  Shall I call mam?            1
24          24         Hi I was at church couldn’t take your call            0
25          25                                         It's k mam            0
26          26  Just to know the tomorrow plan mam.will see to...            0
27          27                    Mam can u send Vignesh number??            1
28          28           Vignesh ML Infoziant.vcf (file attached)            0
29          29                           I was in a meeting sorry            0
30          30                                    Can I cal u mam            1
31          31  Waiting for u r finalization of rates for our ...            1
32          32  If we finiliaze I can work with full involveme...            0
33          33  So what ever may be ..if you think your are co...            0
34          34                           You deleted this message            1
35          35                                     Do the needful            1
36          36  No ma please hold I am in a hot meeting with a...            0
37          37                                     Ok mam thank u            0
38          38  Ramisha we need to talk today i will call u ar...            0
39          39     Be ready to discuss about the ML titles u have            0
40          40                                           Okay mam            0
41          41                                                 ok            0
42          42                                    Mam are u free?            1
43          43   Am at church can call very late or tomorrow only            0
44          44  Kk mam. I will ask Arun brother. Small doubt ....            0
45          45                                             Hi mam            0
46          46                                   Any updates mam?            0
47          47     U might have to start on the WhatsApp analysis            0
48          48            There is one project that got committed            0
49          49                                           Kk mam👍🏻            1

In [18]:
data["Chat"] = data["Chat"].fillna("").astype(str)
data["Flirt_Label"] = pd.to_numeric(data["Flirt_Label"], errors="coerce")
data = data.dropna(subset=["Flirt_Label"])
data["Flirt_Label"] = data["Flirt_Label"].astype(int)

X = data["Chat"]
y = data["Flirt_Label"]

hash_vectorizer = HashingVectorizer(n_features=2**12,alternate_sign=False)

X_hash = hash_vectorizer.transform(X)

print("Hashing Vectorizer Shape:", X_hash.shape)

if y.nunique() == 2 and y.value_counts().min() >= 2:
    X_train, X_test, y_train, y_test = train_test_split(X_hash, y, test_size=0.2,random_state=42, stratify=y)

    hash_model = LogisticRegression(max_iter=1000)
    hash_model.fit(X_train, y_train)

    y_pred = hash_model.predict(X_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, zero_division=0))

    data["Hashing_Prediction"] = hash_model.predict(X_hash)
else:
    print("Classifier not trained: labels contain only one class.")
    print("Add genuine labelled examples from both classes to train.")

display(data.head())

Hashing Vectorizer Shape: (50, 4096)
Accuracy: 0.8
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       0.00      0.00      0.00         2

    accuracy                           0.80        10
   macro avg       0.40      0.50      0.44        10
weighted avg       0.64      0.80      0.71        10

   Message_ID                            Chat  Flirt_Label  Hashing_Prediction
0           0  Hi this is Mabel we just spoke            0                   0
1           1           What’s your full name            0                   0
2           2                  Ramisha Rani K            0                   0
3           3                              Ok            0                   0
4           4          ramisharanik@gmail.com            0                   0

In [19]:
print("Count Vectorizer features:", X_count.shape[1])
print("TF-IDF Vectorizer features:", X_tfidf.shape[1])
print("Hashing Vectorizer features:", X_hash.shape[1])

print("\nNumber of messages:", len(X))
print("Label distribution:")
print(y.value_counts())

Count Vectorizer features: 189
TF-IDF Vectorizer features: 189
Hashing Vectorizer features: 4096

Number of messages: 50
Label distribution:
Flirt_Label
0    42
1     8
Name: count, dtype: int64

In [20]:
if y.nunique() < 2:
    print("Model training cannot proceed.")
    print("All messages have the same label.")
    print("Classifiers need examples from both classes")
    print("(0 = Non-flirtatious, 1 = Flirtatious).")
else:
    print("Both classes are present.")
    print("You can proceed with classifier training.")

Both classes are present.
You can proceed with classifier training.

# 3) Talkative / Less talkative

In [ ]:
df["Name"].value_counts()

# 4) Most active day and time

In [ ]:
df["Date"].value_counts().head(1)

In [ ]:
df["Time"].value_counts().head(5)

# 5) Media count by each person

In [ ]:
media = df[df["Chat"].str.contains("file attached|Media omitted", na=False)]
media["Name"].value_counts()

# 6) Missed calls

In [ ]:
df[df["Chat"].str.contains("Missed", "missed", na=False)]